window.WEDDING = {
  names: 'Юлия и Артём',
  date: '2026-10-17',
  rsvpDeadline: '2026-10-01',
  contact: { name: 'Оля', phone: '+79099624676' },
  rsvpEndpoint: 'https://script.google.com/macros/s/AKfycbxfvSosWJ3rkm_o6kYsjF2q4UnBK6LYxmU0Jr9jkCtEPPl6ac5JGjb2a8fEQNbrB4kl/exec',
  galleryPhotos: [
    'assets/dress-relaxed-couple-brown.webp',
    'assets/dress-code-01.webp',
    'assets/dress-relaxed-olive-brown.webp',
    'assets/dress-code-02.webp',
    'assets/dress-code-03.webp',
    'assets/dress-relaxed-couple-wine.webp',
    'assets/dress-code-04.webp',
    'assets/dress-relaxed-man-olive.webp',
    'assets/dress-code-05.webp',
    'assets/dress-code-06.webp',
    'assets/dress-code-07.webp',
  ],
  // Cropping follows the image, so reordering the gallery preserves its framing.
  galleryCoverPhotos: [
    'assets/dress-code-01.webp',
    'assets/dress-code-02.webp',
    'assets/dress-code-04.webp',
    'assets/dress-code-05.webp',
    'assets/dress-relaxed-couple-brown.webp',
    'assets/dress-relaxed-olive-brown.webp',
    'assets/dress-relaxed-couple-wine.webp',
    'assets/dress-relaxed-man-olive.webp',
  ],
  giftUrl: '',
  chatUrl: '',
  publicUrl: '',
  photoUrl: 'assets/couple-photo-lake.webp',
  venueQuery: 'шатёр Русская Сказка',
  venueMapUrl: 'https://yandex.ru/maps/-/CThXnBl6'
};
